name: grocery_app
description: A comprehensive e-commerce grocery delivery mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design - Core essentials only
  cupertino_icons: ^1.0.6
  razorpay_flutter: ^1.3.6
  google_fonts: ^6.1.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  lottie: ^1.4.3
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.0.5
  get: ^4.6.5

  # HTTP & API
  http: 1.4.0
  dio: ^4.0.6

  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Form & Validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # Navigation & Routing
  go_router: ^7.1.1

  # Image & Media
  image_picker: ^0.8.7+4
  photo_view: ^0.14.0

  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  url_launcher: ^6.1.7
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

  # Security
  crypto: ^3.0.3

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.11.1

  # Sharing
  share_plus: ^10.0.2

  # OPTIONAL PLUGINS
  # mongo_dart: ^0.9.4
  # geolocator: ^8.2.1
  # geocoding: ^2.0.5
  # device_info_plus: ^8.2.2
  # package_info_plus: ^3.1.2
  # firebase_core: ^2.10.0
  # firebase_messaging: ^14.4.1
  # connectivity_plus: ^3.0.6

  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

  # Assets
  assets:
    - images/App_logo.jpg
    - images/logo.png
    - images/google.png
    - images/facebook.jpeg
    - assets/animations/apple.json
    - assets/animations/delivery.json
    - assets/animations/pineapple.json
    - assets/images/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

# App icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"